### ISSUE TITLE
Debug Logging

### ISSUE THREAD

**Issue by aplumafreak500** [aplumafreak500/lumas-ct-pack-launcher#18]
- [ ] USB Gecko Slot A (see #6)
- [ ] USB Gecko Slot B (see #6)
- [ ] Wi-Fi Gecko (see #6)
- [ ] OSReport
- [ ] SD/USB
- [ ] TCP/UDP (see #11)
